# Forward all syslog messages to LIC (UDP port 5514)
# Installed by LIC project. Remove if you want to stop forwarding.
if $syslogfacility-text == 'user' then @@127.0.0.1:5514
if $syslogseverity <= 6 then @@127.0.0.1:5514
& stop
