#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
# Local Incident Commander — Chaos Monkey
# Injects realistic failure events for demo & testing
# ─────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
INBOX_DIR="$REPO_DIR/inbox"

mkdir -p "$INBOX_DIR"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[CHAOS]${NC} $*"; }
ok()    { echo -e "${GREEN}[CHAOS]${NC} $*"; }
warn()  { echo -e "${YELLOW}[CHAOS]${NC} $*"; }
err()   { echo -e "${RED}[CHAOS]${NC} $*"; }

usage() {
    echo "Usage: $0 [--rate <seconds>] [--scenario <all|latency|security|deploy|cpu|db>]"
    exit 1
}

RATE=15
SCENARIO="all"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --rate) RATE="$2"; shift 2 ;;
        --scenario) SCENARIO="$2"; shift 2 ;;
        *) usage ;;
    esac
done

inject_event() {
    local file="$1"
    local src="$REPO_DIR/sample_data/$file"
    local dst="$INBOX_DIR/${file%.*}_$(date +%s).json"
    if [ -f "$src" ]; then
        cp "$src" "$dst"
        ok "Injected: $file"
    else
        warn "File not found: $src"
    fi
}

inject_latency_payload() {
    cat > "$INBOX_DIR/alert_latency_$(date +%s).json" <<EOF
{
  "service": "checkout-service",
  "event_type": "alert",
  "severity": "critical",
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "payload": {"latency_ms": $((RANDOM % 1500 + 500)), "error_rate": $(echo "scale=1; $RANDOM / 32767 * 10" | bc), "endpoint": "/api/checkout"},
  "source": "chaos-monkey",
  "description": "Latency spike generated by chaos monkey"
}
EOF
    ok "Injected synthetic latency alert"
}

inject_security_payload() {
    local ip1="203.0.113.$((RANDOM % 255))"
    local ip2="198.51.100.$((RANDOM % 255))"
    cat > "$INBOX_DIR/alert_security_$(date +%s).json" <<EOF
{
  "service": "auth-service",
  "event_type": "alert",
  "severity": "critical",
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "payload": {"attempt_count": $((RANDOM % 200 + 50)), "source_ips": ["$ip1", "$ip2"], "protocol": "ssh", "is_brute_force": true},
  "source": "chaos-monkey",
  "description": "Brute force attack generated by chaos monkey"
}
EOF
    ok "Injected synthetic security alert"
}

inject_deploy_payload() {
    cat > "$INBOX_DIR/deploy_$(date +%s).txt" <<EOF
deploy: service=checkout-service version=2.$((RANDOM % 10)).$((RANDOM % 100))
timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)
deployed_by: chaos-monkey
environment: production
EOF
    ok "Injected synthetic deploy event"
}

inject_cpu_payload() {
    cat > "$INBOX_DIR/alert_cpu_$(date +%s).json" <<EOF
{
  "service": "checkout-service",
  "event_type": "alert",
  "severity": "high",
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "payload": {"cpu_percent": $((RANDOM % 30 + 70)), "memory_percent": $((RANDOM % 20 + 80)), "host": "checkout-host-01"},
  "source": "chaos-monkey",
  "description": "CPU saturation generated by chaos monkey"
}
EOF
    ok "Injected synthetic CPU alert"
}

inject_db_payload() {
    cat > "$INBOX_DIR/alert_db_$(date +%s).json" <<EOF
{
  "service": "checkout-service",
  "event_type": "alert",
  "severity": "high",
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "payload": {"db_connections": $((RANDOM % 30 + 70)), "db_connection_limit": 100, "db_query_latency_ms": $((RANDOM % 500 + 300))},
  "source": "chaos-monkey",
  "description": "DB pool pressure generated by chaos monkey"
}
EOF
    ok "Injected synthetic DB alert"
}

info "Chaos Monkey starting — injecting events every ${RATE}s (scenario: $SCENARIO)"
info "Source data: $REPO_DIR/sample_data/"
info "Inbox:       $INBOX_DIR/"
info "Press Ctrl+C to stop"
echo ""

# Preload with static sample data
if [ "$SCENARIO" = "all" ] || [ "$SCENARIO" = "latency" ]; then
    inject_event "alert_api_latency.json"
fi
if [ "$SCENARIO" = "all" ] || [ "$SCENARIO" = "security" ]; then
    inject_event "ssh_brute_force.json"
fi
if [ "$SCENARIO" = "all" ] || [ "$SCENARIO" = "deploy" ]; then
    inject_event "deploy_log.txt"
fi
if [ "$SCENARIO" = "all" ] || [ "$SCENARIO" = "cpu" ]; then
    inject_event "alert_cpu_spike.json"
fi
if [ "$SCENARIO" = "all" ] || [ "$SCENARIO" = "db" ]; then
    inject_event "alert_db_pool.json"
fi
echo ""

while true; do
    sleep "$RATE"
    echo ""
    case "$SCENARIO" in
        all)     inject_latency_payload; sleep 2; inject_cpu_payload ;;
        latency) inject_latency_payload ;;
        security) inject_security_payload ;;
        deploy)  inject_deploy_payload ;;
        cpu)     inject_cpu_payload ;;
        db)      inject_db_payload ;;
    esac
done
