import json
import logging
from typing import Dict, Optional
from src.local_model import generate as local_generate, TRANSFORMERS_AVAILABLE
from src.openclaw_adapter import call_llm as openclaw_call_llm, is_available as openclaw_available

logger = logging.getLogger(__name__)

LLM_ENDPOINT = "http://localhost:8000/v1"
LLM_MODEL = "/home/dell/repos/Qwen3.6-35B-A3B-NVFP4/"


def configure(endpoint: str = None, model: str = None):
    global LLM_ENDPOINT, LLM_MODEL
    if endpoint:
        LLM_ENDPOINT = endpoint
    if model:
        LLM_MODEL = model


def call_llm(prompt: str, max_tokens: int = 300) -> str:
    if openclaw_available():
        try:
            result = openclaw_call_llm(prompt)
            if result:
                return result
        except Exception as e:
            logger.warning(f"OpenClaw LLM call failed: {e}")
    try:
        import requests
        response = requests.post(
            f"{LLM_ENDPOINT}/chat/completions",
            json={
                "model": LLM_MODEL,
                "messages": [
                    {"role": "system", "content": "You are an SRE incident commander. Be concise and accurate."},
                    {"role": "user", "content": prompt},
                ],
                "max_tokens": max_tokens,
                "temperature": 0.3,
            },
            timeout=60,
        )
        response.raise_for_status()
        data = response.json()
        return data["choices"][0]["message"]["content"].strip()
    except (ImportError, ConnectionError, TimeoutError, KeyError, Exception) as e:
        logger.warning(f"LLM endpoint call failed: {e}")
    if TRANSFORMERS_AVAILABLE:
        try:
            return local_generate(prompt, max_tokens, think=True)
        except Exception as e2:
            logger.warning(f"Local model fallback also failed: {e2}")
    raise ConnectionError("LLM unavailable: all backends failed")


def generate_brief(incident: Dict) -> str:
    try:
        prompt = _build_brief_prompt(incident)
        brief = call_llm(prompt, max_tokens=400)
        return brief
    except (ConnectionError, TimeoutError):
        return _fallback_brief(incident)


def _build_brief_prompt(incident: Dict) -> str:
    events_str = json.dumps(incident.get("correlated_events", []), indent=2)
    return f"""Generate a concise executive incident brief (3-5 sentences) for:

Incident ID: {incident.get('incident_id')}
Service: {incident.get('service')}
Severity: {incident.get('severity')}
Root Cause: {incident.get('probable_root_cause', 'Unknown')}
Recommended Action: {incident.get('recommended_action', 'None')}
Events:
{events_str}

Brief format:
- What happened
- Impact
- Root cause
- Recommended action
- Whether human approval is required"""


def _fallback_brief(incident: Dict) -> str:
    incident_id = incident.get("incident_id", "UNKNOWN")
    service = incident.get("service", "unknown")
    severity = incident.get("severity", "Medium")
    root_cause = incident.get("probable_root_cause", "No root cause determined")
    action = incident.get("recommended_action", "No action recommended")
    requires = incident.get("requires_human_approval", True)
    ts = incident.get("timestamp", "unknown time")

    events_summary = []
    for e in incident.get("correlated_events", []):
        events_summary.append(f"- {e.get('event_type', 'log')} at {e.get('timestamp', '?')}: {e.get('summary', '')}")

    return f"""INCIDENT BRIEF: {incident_id}
──────────────────────────────────────────────
Severity: {severity}
Service:  {service}
Time:     {ts}

WHAT HAPPENED:
{chr(10).join(events_summary) if events_summary else 'Multiple correlated signals detected.'}

ROOT CAUSE:
{root_cause}

RECOMMENDED ACTION:
{action}

HUMAN APPROVAL: {"REQUIRED" if requires else "NOT REQUIRED"}

This brief was auto-generated by Local Incident Commander.
LLM endpoint was unavailable — deterministic template used."""
